Repository gardener/diki, pull requests merged in 2023-09, with the labels that each got.

#6 replace symlink with copy of the apache license
  LICENSE
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#3 Improve `ETCD` peer options rules
  pkg/kubernetes/config/etcd.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242380.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242380_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242426.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242426_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242432.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242432_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242433.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242433_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#2 Fix `ssh` rules
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242393.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242393_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242394.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242394_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#11 Add script to generate new `DISA k8s STIGs` dir and ruleset file
  hack/gen-new-disak8sstig-version.sh
  pkg/provider/gardener/ruleset/disak8sstig/v1r8_ruleset.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#12 Use label selector instead of name prefix for rule `242414`
  example/config/gardener.yaml
  pkg/kubernetes/utils/utils.go
  pkg/kubernetes/utils/utils_test.go
  pkg/provider/gardener/internal/utils/utils.go
  pkg/provider/gardener/internal/utils/utils_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242414.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/242414_test.go
Labels: reviewed/lgtm, needs/ok-to-test, needs/review, size/m

#17 [Kubernetes STIG v1r10] Remove 242458 and 242468 rules
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242458.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242458_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242468.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242468_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/options.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10_ruleset.go
Labels: needs/ok-to-test, needs/review, size/m

#16 add version command to diki
  .dockerignore
  Dockerfile
  cmd/diki/app/app.go
  hack/get-build-ld-flags.sh
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#20 [Kubernetes STIG v1r10] Update 242382 and 242435 rules
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242382.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242382_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242435.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242435_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#19 Build recipes
  Makefile
  hack/build.sh
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#25 Fix file permission comparison in `MatchFilePermissionsAndOwnersCases`
  pkg/provider/gardener/internal/utils/utils.go
  pkg/provider/gardener/internal/utils/utils_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/node_files_permissions_and_owner_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/node_files_permissions_and_owner_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#24 [Kubernetes STIG v1r10] Update 242397 rule
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242397.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242397_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#22 [Kubernetes STIG v1r10] Update 242391 and 242392 rules
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242391.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242391_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242392.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242392_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#23 [Kubernetes STIG v1r10] Change severity of 245543 and 245544 rules
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/245543.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/245544.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#27 Add link to certificate-rotation documentation
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242424.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242425.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/node_files_permissions_and_owner.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#28 Shrink `html` reports
  pkg/report/templates/html/merged_report.html
  pkg/report/templates/html/report.html
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m

#30 Improve skip message for 242466 and 242467 rule
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242466.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242466_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242467.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242467_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#29 Fix `node-files` rule Name
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/node_files_permissions_and_owner.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r8/node_files_permissions_and_owner.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#26 [Kubernetes STIG v1r10] Dynamically find `kubelet` files
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242424_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/242425_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/node_files_permissions_and_owner.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/node_files_permissions_and_owner_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m

#31 Remove replace directives in `go.mod` file
  go.mod
  go.sum
  vendor/modules.txt
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#34 Add `v1r10` to `FromGenericConfig`
  pkg/provider/gardener/ruleset/disak8sstig/ruleset.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#32 Add `diki-uploader` workflow action
  .github/workflows/upload-diki-binaries.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#35 Shrink size of `html` reports
  pkg/report/templates/html/merged_report.html
  pkg/report/templates/html/report.html
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
