Repository gardener/diki, pull requests merged in 2024-10, with the labels that each got.

#311 Improve consistency in log messages
  pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
  pkg/provider/gardener/ruleset/disak8sstig/v2r1_ruleset.go
  pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
  pkg/provider/managedk8s/ruleset/disak8sstig/v2r1_ruleset.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/v2r1_ruleset.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l

#308 Add `Security Hardened Shoot Cluster` ruleset version `v0.1.0`
  docs/providers/garden.md
  docs/providers/gardener.md
  docs/providers/managedk8s.md
  docs/providers/virtualgarden.md
  docs/rulesets/disa-k8s-stig/ruleset.md
  docs/rulesets/security-hardened-shoot-cluster/ruleset.md
  docs/rulesets/security-hardened-shoot-cluster/security-hardened-shoot-cluster-v0.1.0.yaml
  example/config/garden.yaml
  pkg/provider/garden/ruleset/securityhardenedshoot/ruleset.go
  pkg/provider/garden/ruleset/securityhardenedshoot/v00_ruleset.go
  pkg/provider/garden/ruleset/securityhardenedshoot/v01_ruleset.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l

#317 Simplify some code
  pkg/kubernetes/utils/utils.go
  pkg/report/merged_report.go
  pkg/report/render.go
  pkg/report/report.go
Labels: reviewed/lgtm, needs/ok-to-test, needs/review, size/xs

#318 Generated summary reports should contain provider metadata
  cmd/diki/app/app.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#319 Add REUSE check github action
  .github/workflows/reuse-check.yaml
  docs/rulesets/security-hardened-shoot-cluster/security-hardened-shoot-cluster-v0.1.0.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#316 Consistently use namespaceMatchLabels across rules
  example/config/managedk8s.yaml
  example/guides/partial-disa-k8s-stig-shoot.yaml
  pkg/provider/gardener/ruleset/disak8sstig/rules/242414_test.go
  pkg/provider/gardener/ruleset/disak8sstig/rules/242415_test.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
  pkg/provider/gardener/ruleset/disak8sstig/v2r1_ruleset.go
  pkg/provider/managedk8s/ruleset/disak8sstig/rules/242414_test.go
  pkg/provider/managedk8s/ruleset/disak8sstig/rules/242415_test.go
  pkg/shared/ruleset/disak8sstig/option/options.go
  pkg/shared/ruleset/disak8sstig/option/options_test.go
  pkg/shared/ruleset/disak8sstig/rules/242383.go
  pkg/shared/ruleset/disak8sstig/rules/242383_test.go
  pkg/shared/ruleset/disak8sstig/rules/242417.go
  pkg/shared/ruleset/disak8sstig/rules/242417_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xl

#321 DISA K8s STIG rule 242442 does not parse imageID correctly
  go.mod
  go.sum
  pkg/provider/gardener/ruleset/disak8sstig/rules/242442.go
  pkg/provider/gardener/ruleset/disak8sstig/rules/242442_test.go
  pkg/provider/managedk8s/ruleset/disak8sstig/rules/242442.go
  pkg/provider/managedk8s/ruleset/disak8sstig/rules/242442_test.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/rules/242442.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/rules/242442_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l

#320 Fixed broken links - 2024.10
  docs/usage/partial-disa-k8s-stig-shoot.md
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#325 Check for proxy container if kube-proxy is not present
  pkg/internal/utils/utils.go
  pkg/internal/utils/utils_test.go
  pkg/kubernetes/utils/utils.go
  pkg/kubernetes/utils/utils_test.go
  pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go
  pkg/provider/managedk8s/ruleset/disak8sstig/rules/242400.go
  pkg/provider/managedk8s/ruleset/disak8sstig/rules/242400_test.go
  pkg/shared/ruleset/disak8sstig/retryerrors/retryerrors_test.go
  pkg/shared/ruleset/disak8sstig/rules/242447.go
  pkg/shared/ruleset/disak8sstig/rules/242447_test.go
  pkg/shared/ruleset/disak8sstig/rules/242448.go
  pkg/shared/ruleset/disak8sstig/rules/242448_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m

#326 Add additional comment suggestions to the GetContainer util methods
  pkg/internal/utils/utils.go
  pkg/kubernetes/utils/utils.go
Labels: needs/ok-to-test, needs/changes, needs/review, size/xs

#333 Enable gosec for SAST scans
  .ci/pipeline_definitions
  .gitignore
  Makefile
  hack/sast.sh
  pkg/internal/stringgen/generator.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s, ci/broken-pipeline-definition

#334 Implement DISA K8s STIG 242390 for Managed K8s provider
  pkg/provider/managedk8s/ruleset/disak8sstig/rules/242390.go
  pkg/provider/managedk8s/ruleset/disak8sstig/rules/242390_test.go
  pkg/provider/managedk8s/ruleset/disak8sstig/v2r1_ruleset.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m
