Repository gardener/diki, pull requests merged in 2024-05, with the labels that each got.

#233 Add diki release version to generated json report
  pkg/report/report.go
Labels: reviewed/lgtm, needs/ok-to-test, needs/review, size/xs

#223 Add `args` field `opsPodLabels` to all providers
  example/config/gardener.yaml
  example/config/managedk8s.yaml
  example/config/virtualgarden.yaml
  pkg/kubernetes/pod/pod.go
  pkg/kubernetes/pod/pod_test.go
  pkg/provider/builder/gardener.go
  pkg/provider/builder/managedk8s.go
  pkg/provider/builder/virtualgarden.go
  pkg/provider/gardener/options.go
  pkg/provider/gardener/provider.go
  pkg/provider/gardener/ruleset/disak8sstig/options.go
  pkg/provider/gardener/ruleset/disak8sstig/ruleset.go
  pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
  pkg/provider/managedk8s/options.go
  pkg/provider/managedk8s/provider.go
  pkg/provider/managedk8s/ruleset/disak8sstig/options.go
  pkg/provider/managedk8s/ruleset/disak8sstig/ruleset.go
  pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
  pkg/provider/virtualgarden/options.go
  pkg/provider/virtualgarden/provider.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/options.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/ruleset.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go
Labels: reviewed/lgtm, needs/ok-to-test, needs/review, size/m

#236 Fix diki html report truncate
  cmd/diki/app/app.go
Labels: needs/ok-to-test, needs/review, size/xs

#235 Add report metadata
  cmd/diki/app/app.go
  example/config/gardener.yaml
  example/config/managedk8s.yaml
  example/config/virtualgarden.yaml
  pkg/config/config.go
  pkg/report/merged_report.go
  pkg/report/merged_report_test.go
  pkg/report/render.go
  pkg/report/report.go
  pkg/report/templates/html/_styles.tpl
  pkg/report/templates/html/merged_report.html
  pkg/report/templates/html/output.css
  pkg/report/templates/html/report.html
Labels: reviewed/lgtm, needs/ok-to-test, needs/second-opinion, size/l

#237 Fix link in README
  README.md
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#238 Add skip rule example
  example/config/gardener.yaml
  example/config/managedk8s.yaml
  example/config/virtualgarden.yaml
Labels: needs/ok-to-test, needs/review, size/xs
