Repository gardener/diki, pull requests merged in 2024-04, with the labels that each got.

#199 Add generate diff command to create html difference reports
  .reuse/dep5
  README.md
  cmd/diki/app/app.go
  pkg/report/difference.go
  pkg/report/difference_test.go
  pkg/report/render.go
  pkg/report/templates/html/difference_report.html
  pkg/report/templates/html/merged_report.html
  pkg/report/templates/html/report.html
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l

#203 Rm redundant component-descriptor trait
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#204 [DISA K8s STIG] Fix rule 242451 validation for managed k8s provider
  pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242451.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#205 [release-v0.6] Automated cherry pick of #204: [DISA K8s STIG] Fix rule 242451 validation for managed k8s provider
  pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242451.go
Labels: needs/ok-to-test, needs/review, size/xs

#212 [DISA K8s STIG] Fix rule 242452 for gardener provider
  pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
Labels: reviewed/lgtm, needs/ok-to-test, needs/review, size/xs

#211 Add prefix to tailwind css classes
  pkg/report/templates/html/_styles.tpl
  pkg/report/templates/html/difference_report.html
  pkg/report/templates/html/merged_report.html
  pkg/report/templates/html/output.css
  pkg/report/templates/html/report.html
  tailwind.config.js
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#216 Sort rules by ID in html reports
  pkg/report/merged_report.go
  pkg/report/report.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#215 Minimise `diki-ops` container
  Dockerfile
Labels: needs/ok-to-test, needs/review, size/xs

#219 Use statics messages for logs
  pkg/shared/provider/provider.go
  pkg/shared/ruleset/ruleset.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#220 [Docu] Fix diki commands in partial DISA K8s STIG guide
  docs/usage/partial-disa-k8s-stig-shoot.md
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
