Repository gardener/diki, pull requests merged in 2025-01, with the labels that each got.

#406 Add a guide documentation for validating the Security Hardened Kubernetes ruleset against a Gardener Shoot Cluster
  docs/usage/security-hardened-k8s-shoot.md
  example/guides/security-hardened-k8s-shoot.yaml
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/m

#415 Reference correct rule in Security Hardened Shoot cluter guide
  docs/rulesets/security-hardened-shoot-cluster/ruleset.md
Labels: needs/ok-to-test

#410 Add support for V2R2 of the DISA K8s STIG ruleset
  README.md
  docs/providers/gardener.md
  docs/providers/managedk8s.md
  docs/providers/virtualgarden.md
  example/config/gardener.yaml
  example/config/managedk8s.yaml
  example/config/virtualgarden.yaml
  example/guides/disa-k8s-stig-shoot.yaml
  hack/run.sh
  pkg/provider/gardener/ruleset/disak8sstig/ruleset.go
  pkg/provider/gardener/ruleset/disak8sstig/v2r2_ruleset.go
  pkg/provider/managedk8s/ruleset/disak8sstig/ruleset.go
  pkg/provider/managedk8s/ruleset/disak8sstig/v2r2_ruleset.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/ruleset.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/v2r2_ruleset.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#418 Add a minimal status option to the report generating command
  cmd/diki/app/app.go
  pkg/report/report.go
  pkg/report/report_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m

#413 Refactor Rules that can potentially return empty CheckResults to handle their edge cases.
  pkg/provider/managedk8s/ruleset/disak8sstig/rules/242415.go
  pkg/provider/managedk8s/ruleset/disak8sstig/rules/242415_test.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2001.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2001_test.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2003.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2003_test.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2004.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2004_test.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2005.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2005_test.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2006.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2006_test.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2007.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2007_test.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2008.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2008_test.go
  pkg/shared/ruleset/disak8sstig/rules/242404.go
  pkg/shared/ruleset/disak8sstig/rules/242404_test.go
  pkg/shared/ruleset/disak8sstig/rules/242417.go
  pkg/shared/ruleset/disak8sstig/rules/242417_test.go
  pkg/shared/ruleset/ruleset.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m

#412 Add a show command to the Diki CLI
  cmd/diki/app/app.go
  cmd/diki/main.go
  pkg/metadata/metadata.go
  pkg/provider/builder/garden.go
  pkg/provider/builder/gardener.go
  pkg/provider/builder/managedk8s.go
  pkg/provider/builder/virtualgarden.go
  pkg/provider/garden/provider.go
  pkg/provider/garden/ruleset/securityhardenedshoot/ruleset.go
  pkg/provider/gardener/provider.go
  pkg/provider/gardener/ruleset/disak8sstig/ruleset.go
  pkg/provider/managedk8s/provider.go
  pkg/provider/managedk8s/ruleset/disak8sstig/ruleset.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/ruleset.go
  pkg/provider/provider.go
  pkg/provider/virtualgarden/provider.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/ruleset.go
Labels: reviewed/lgtm, needs/ok-to-test, size/l

#424 [Security Hardened Kubernetes Cluster] Rule 2000 add rule options
  example/config/managedk8s.yaml
  example/guides/security-hardened-k8s-shoot.yaml
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000_test.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/options.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/v01_ruleset.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m
