Repository gardener/diki, pull requests merged in 2025-08, with the labels that each got.

#546 Fix `as` casing to match `FROM` casing
  Dockerfile
Labels: reviewed/ok-to-test, needs/review, size/xs

#545 Convert dep5 to REUSE.toml
  .reuse/dep5
  REUSE.toml
Labels: reviewed/ok-to-test, needs/review, size/s

#544 Configure rule options for rules 2000 of the Security Hardened Shoot Cluster ruleset and 242390 of the DISA STIG ruleset
  example/config/garden.yaml
  example/config/gardener.yaml
  example/config/virtualgarden.yaml
  pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go
  pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000_test.go
  pkg/provider/garden/ruleset/securityhardenedshoot/rules/options.go
  pkg/provider/garden/ruleset/securityhardenedshoot/v01_ruleset.go
  pkg/provider/garden/ruleset/securityhardenedshoot/v02_ruleset.go
  pkg/provider/gardener/ruleset/disak8sstig/rules/options.go
  pkg/provider/gardener/ruleset/disak8sstig/v2r2_ruleset.go
  pkg/provider/gardener/ruleset/disak8sstig/v2r3_ruleset.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/rules/options.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/v2r2_ruleset.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/v2r3_ruleset.go
  pkg/shared/ruleset/disak8sstig/rules/242390.go
  pkg/shared/ruleset/disak8sstig/rules/242390_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xl

#563 include diki-binaries as release-assets + refactor package-publishing
  .github/workflows/build.yaml
  .github/workflows/export-digests-from-component-descriptor.sh
  .github/workflows/publish-to-package-repositories.yaml
  .github/workflows/release.yaml
  .github/workflows/upload-diki-binaries.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/review, needs/second-opinion, size/l

#569 Use `ubuntu-latest` for all diki binaries
  .github/workflows/build.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#571 Use ubuntu-latest for all diki builds (#569)
  .github/workflows/build.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#573 Disable CGO on diki build workflow
  .github/workflows/build.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#561 Refactor `unknown provider|ruleset|ruleset version` error messages to refer the user to the diki show command
  pkg/provider/builder/garden.go
  pkg/provider/builder/gardener.go
  pkg/provider/builder/managedk8s.go
  pkg/provider/builder/virtualgarden.go
  pkg/provider/garden/ruleset/securityhardenedshoot/ruleset.go
  pkg/provider/gardener/ruleset/disak8sstig/ruleset.go
  pkg/provider/managedk8s/ruleset/disak8sstig/ruleset.go
  pkg/provider/managedk8s/ruleset/securityhardenedk8s/ruleset.go
  pkg/provider/virtualgarden/ruleset/disak8sstig/ruleset.go
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs
